service: visitorcounter

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    PUSHER_APP_ID: 1015757
    PUSHER_APP_KEY: 58228e5883fed44d8745
    PUSHER_APP_SECRET: c698364d0273e0a4fcd6
    PUSHER_APP_CLUSTER: us3

functions:
  home:
    handler: handler.home
    events:
    - http:
        path: /
        method: get
        cors: true
  webhook:
    handler: handler.webhook
    events:
    - http:
        path: /webhook
        method: post
        cors: true      
